"""
Demo dáta simulujúce reálne akciové ponuky slovenských obchodov.
V produkcii by tieto dáta pochádzali zo scrapingu letákových webov.
"""

DEMO_DEALS = [
    # === MLIEČNE VÝROBKY ===
    {
        "name": "Mlieko polotučné 1,5% 1l",
        "price": 0.89,
        "original_price": 1.19,
        "unit": "1 l",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-22",
        "discount_percent": 25,
    },
    {
        "name": "Mlieko čerstvé polotučné 1l",
        "price": 0.99,
        "original_price": 1.29,
        "unit": "1 l",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-22",
        "discount_percent": 23,
    },
    {
        "name": "Mlieko polotučné Kunín 1,5% 1l",
        "price": 1.09,
        "original_price": 1.39,
        "unit": "1 l",
        "store": "Billa",
        "store_id": "billa",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-20",
        "discount_percent": 22,
    },
    {
        "name": "Mlieko polotučné 1l",
        "price": 0.95,
        "original_price": 1.25,
        "unit": "1 l",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-21",
        "discount_percent": 24,
    },
    {
        "name": "Maslo 250g",
        "price": 1.49,
        "original_price": 2.19,
        "unit": "250 g",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-22",
        "discount_percent": 32,
    },
    {
        "name": "Maslo Président 250g",
        "price": 1.79,
        "original_price": 2.49,
        "unit": "250 g",
        "store": "Billa",
        "store_id": "billa",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-20",
        "discount_percent": 28,
    },
    {
        "name": "Maslo čerstvé 250g",
        "price": 1.59,
        "original_price": 2.29,
        "unit": "250 g",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-22",
        "discount_percent": 31,
    },
    {
        "name": "Jogurt biely 150g",
        "price": 0.39,
        "original_price": 0.59,
        "unit": "150 g",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-22",
        "discount_percent": 34,
    },
    {
        "name": "Jogurt grécky 150g",
        "price": 0.69,
        "original_price": 0.99,
        "unit": "150 g",
        "store": "Billa",
        "store_id": "billa",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-20",
        "discount_percent": 30,
    },
    {
        "name": "Syr Eidam 30% plátky 100g",
        "price": 0.79,
        "original_price": 1.19,
        "unit": "100 g",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-22",
        "discount_percent": 34,
    },
    {
        "name": "Syr Eidam 30% blok 200g",
        "price": 1.29,
        "original_price": 1.89,
        "unit": "200 g",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Mliečne výrobky",
        "valid_until": "2026-03-21",
        "discount_percent": 32,
    },

    # === MÄSO ===
    {
        "name": "Kuracie prsia 1kg",
        "price": 4.99,
        "original_price": 7.49,
        "unit": "1 kg",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Mäso",
        "valid_until": "2026-03-19",
        "discount_percent": 33,
    },
    {
        "name": "Kuracie prsia bez kosti 1kg",
        "price": 5.49,
        "original_price": 7.99,
        "unit": "1 kg",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Mäso",
        "valid_until": "2026-03-22",
        "discount_percent": 31,
    },
    {
        "name": "Kuracie prsia chladené 1kg",
        "price": 5.29,
        "original_price": 7.69,
        "unit": "1 kg",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Mäso",
        "valid_until": "2026-03-21",
        "discount_percent": 31,
    },
    {
        "name": "Kuracie stehná 1kg",
        "price": 2.99,
        "original_price": 4.49,
        "unit": "1 kg",
        "store": "Penny Market",
        "store_id": "penny",
        "category": "Mäso",
        "valid_until": "2026-03-20",
        "discount_percent": 33,
    },
    {
        "name": "Bravčový karé 1kg",
        "price": 4.49,
        "original_price": 6.99,
        "unit": "1 kg",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Mäso",
        "valid_until": "2026-03-19",
        "discount_percent": 36,
    },
    {
        "name": "Bravčové karé bez kosti 1kg",
        "price": 4.99,
        "original_price": 7.29,
        "unit": "1 kg",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Mäso",
        "valid_until": "2026-03-22",
        "discount_percent": 32,
    },
    {
        "name": "Hovädzie zadné 1kg",
        "price": 8.99,
        "original_price": 12.49,
        "unit": "1 kg",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Mäso",
        "valid_until": "2026-03-21",
        "discount_percent": 28,
    },
    {
        "name": "Šunka od kosti krájaná 100g",
        "price": 0.99,
        "original_price": 1.49,
        "unit": "100 g",
        "store": "Billa",
        "store_id": "billa",
        "category": "Mäso",
        "valid_until": "2026-03-20",
        "discount_percent": 34,
    },

    # === PEČIVO ===
    {
        "name": "Chlieb ražný 500g",
        "price": 0.89,
        "original_price": 1.29,
        "unit": "500 g",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Pečivo",
        "valid_until": "2026-03-22",
        "discount_percent": 31,
    },
    {
        "name": "Chlieb celozrnný 400g",
        "price": 1.09,
        "original_price": 1.59,
        "unit": "400 g",
        "store": "Billa",
        "store_id": "billa",
        "category": "Pečivo",
        "valid_until": "2026-03-20",
        "discount_percent": 31,
    },
    {
        "name": "Rožky pšeničné 10ks",
        "price": 0.79,
        "original_price": 1.09,
        "unit": "10 ks",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Pečivo",
        "valid_until": "2026-03-22",
        "discount_percent": 28,
    },

    # === OVOCIE A ZELENINA ===
    {
        "name": "Banány 1kg",
        "price": 0.99,
        "original_price": 1.49,
        "unit": "1 kg",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-19",
        "discount_percent": 34,
    },
    {
        "name": "Banány 1kg",
        "price": 1.09,
        "original_price": 1.49,
        "unit": "1 kg",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-22",
        "discount_percent": 27,
    },
    {
        "name": "Banány 1kg",
        "price": 1.15,
        "original_price": 1.55,
        "unit": "1 kg",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-21",
        "discount_percent": 26,
    },
    {
        "name": "Jablká červené 1kg",
        "price": 1.29,
        "original_price": 1.99,
        "unit": "1 kg",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-22",
        "discount_percent": 35,
    },
    {
        "name": "Jablká Golden 1kg",
        "price": 1.39,
        "original_price": 1.99,
        "unit": "1 kg",
        "store": "Billa",
        "store_id": "billa",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-20",
        "discount_percent": 30,
    },
    {
        "name": "Rajčiny 500g",
        "price": 1.19,
        "original_price": 1.79,
        "unit": "500 g",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-22",
        "discount_percent": 34,
    },
    {
        "name": "Zemiaky 2kg",
        "price": 1.49,
        "original_price": 2.29,
        "unit": "2 kg",
        "store": "COOP Jednota",
        "store_id": "coop",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-22",
        "discount_percent": 35,
    },
    {
        "name": "Paprika mix 500g",
        "price": 1.59,
        "original_price": 2.49,
        "unit": "500 g",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Ovocie a zelenina",
        "valid_until": "2026-03-19",
        "discount_percent": 36,
    },

    # === NÁPOJE ===
    {
        "name": "Coca-Cola 2l",
        "price": 1.29,
        "original_price": 1.89,
        "unit": "2 l",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Nápoje",
        "valid_until": "2026-03-22",
        "discount_percent": 32,
    },
    {
        "name": "Coca-Cola 2l",
        "price": 1.39,
        "original_price": 1.89,
        "unit": "2 l",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Nápoje",
        "valid_until": "2026-03-22",
        "discount_percent": 26,
    },
    {
        "name": "Coca-Cola 2l",
        "price": 1.49,
        "original_price": 1.99,
        "unit": "2 l",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Nápoje",
        "valid_until": "2026-03-21",
        "discount_percent": 25,
    },
    {
        "name": "Minerálka Rajec 1,5l",
        "price": 0.45,
        "original_price": 0.69,
        "unit": "1.5 l",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Nápoje",
        "valid_until": "2026-03-22",
        "discount_percent": 35,
    },
    {
        "name": "Minerálka Rajec 1,5l",
        "price": 0.49,
        "original_price": 0.69,
        "unit": "1.5 l",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Nápoje",
        "valid_until": "2026-03-21",
        "discount_percent": 29,
    },
    {
        "name": "Pivo Zlatý Bažant 12° 0,5l",
        "price": 0.69,
        "original_price": 0.99,
        "unit": "0.5 l",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Nápoje",
        "valid_until": "2026-03-22",
        "discount_percent": 30,
    },
    {
        "name": "Pivo Zlatý Bažant 12° 0,5l",
        "price": 0.75,
        "original_price": 0.99,
        "unit": "0.5 l",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Nápoje",
        "valid_until": "2026-03-22",
        "discount_percent": 24,
    },

    # === POTRAVINY ===
    {
        "name": "Ryža dlhozrnná 1kg",
        "price": 1.09,
        "original_price": 1.59,
        "unit": "1 kg",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Potraviny",
        "valid_until": "2026-03-22",
        "discount_percent": 31,
    },
    {
        "name": "Cestoviny špagety 500g",
        "price": 0.69,
        "original_price": 1.09,
        "unit": "500 g",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Potraviny",
        "valid_until": "2026-03-22",
        "discount_percent": 37,
    },
    {
        "name": "Cestoviny penne 500g",
        "price": 0.79,
        "original_price": 1.09,
        "unit": "500 g",
        "store": "Billa",
        "store_id": "billa",
        "category": "Potraviny",
        "valid_until": "2026-03-20",
        "discount_percent": 28,
    },
    {
        "name": "Olej slnečnicový 1l",
        "price": 1.49,
        "original_price": 2.19,
        "unit": "1 l",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Potraviny",
        "valid_until": "2026-03-22",
        "discount_percent": 32,
    },
    {
        "name": "Olej slnečnicový 1l",
        "price": 1.59,
        "original_price": 2.19,
        "unit": "1 l",
        "store": "Penny Market",
        "store_id": "penny",
        "category": "Potraviny",
        "valid_until": "2026-03-20",
        "discount_percent": 27,
    },
    {
        "name": "Múka hladká 1kg",
        "price": 0.59,
        "original_price": 0.89,
        "unit": "1 kg",
        "store": "COOP Jednota",
        "store_id": "coop",
        "category": "Potraviny",
        "valid_until": "2026-03-22",
        "discount_percent": 34,
    },
    {
        "name": "Cukor kryštálový 1kg",
        "price": 0.89,
        "original_price": 1.29,
        "unit": "1 kg",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Potraviny",
        "valid_until": "2026-03-22",
        "discount_percent": 31,
    },
    {
        "name": "Nutella 750g",
        "price": 3.99,
        "original_price": 5.99,
        "unit": "750 g",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Potraviny",
        "valid_until": "2026-03-22",
        "discount_percent": 33,
    },
    {
        "name": "Nutella 400g",
        "price": 2.99,
        "original_price": 3.99,
        "unit": "400 g",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Potraviny",
        "valid_until": "2026-03-21",
        "discount_percent": 25,
    },

    # === DROGÉRIA ===
    {
        "name": "Toaletný papier 3-vrstvový 8ks",
        "price": 2.49,
        "original_price": 3.99,
        "unit": "8 ks",
        "store": "Lidl",
        "store_id": "lidl",
        "category": "Drogéria",
        "valid_until": "2026-03-22",
        "discount_percent": 38,
    },
    {
        "name": "Toaletný papier 3-vrstvový 16ks",
        "price": 4.49,
        "original_price": 6.99,
        "unit": "16 ks",
        "store": "Kaufland",
        "store_id": "kaufland",
        "category": "Drogéria",
        "valid_until": "2026-03-22",
        "discount_percent": 36,
    },
    {
        "name": "Prací prášok 3kg",
        "price": 4.99,
        "original_price": 7.99,
        "unit": "3 kg",
        "store": "Tesco",
        "store_id": "tesco",
        "category": "Drogéria",
        "valid_until": "2026-03-21",
        "discount_percent": 38,
    },
]
